import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const db=createClient('https://kwadhzmdaakxkztggigm.supabase.co','sb_publishable_8kEj3zY3ebOMZDYutUBv5A_wbLELNIM',{auth:{autoRefreshToken:true,persistSession:true}});
const el=id=>document.getElementById(id);let member=null,user=null,stays=[],view='students';
function status(s,error=false){const node=el('notice');node.textContent=s;node.className=error?'danger':''}
function field(label,id,type='text',required=true){return '<label for="'+id+'">'+label+'</label><input id="'+id+'" type="'+type+'" '+(required?'required':'')+'>'}
function optionList(){return stays.map(s=>'<option value="'+s.id+'">'+escapeHtml(s.crl_residents?.full_name||'Acolhido')+'</option>').join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function init(){const result=await db.auth.getUser();if(result.error||!result.data.user)return;user=result.data.user;const r=await db.from('crl_members').select('institution_id,display_name,role,active').eq('auth_user_id',user.id).eq('active',true).maybeSingle();if(r.error||!r.data){await signOut();el('loginMessage').textContent='Conta ainda não habilitada para a CRL.';return}member=r.data;el('loginPanel').classList.add('hide');el('appPanel').classList.remove('hide');el('identity').textContent=member.display_name+' · '+(member.role==='admin'?'Administrador':'Monitor');await refresh()}
async function signOut(){await db.auth.signOut();member=null;user=null;el('appPanel').classList.add('hide');el('loginPanel').classList.remove('hide');el('password').value=''}
el('logout').onclick=signOut;
el('loginForm').onsubmit=async e=>{e.preventDefault();const username=el('username').value.trim().toLowerCase();if(!/^[a-z0-9._-]{3,60}$/.test(username))return;el('loginButton').disabled=true;el('loginMessage').textContent='Verificando acesso...';const r=await db.auth.signInWithPassword({email:username+'@crl.ddsinovacao.com.br',password:el('password').value});if(r.error)el('loginMessage').textContent='Usuário ou senha inválidos.';else{el('loginMessage').textContent='';await init()}el('loginButton').disabled=false};
async function refresh(){const r=await db.from('crl_stays').select('id,resident_id,admission_date,crl_residents(full_name)').eq('institution_id',member.institution_id).eq('status','active').order('admission_date',{ascending:false});if(r.error){status('Falha na consulta dos acolhidos.',true);return}stays=r.data||[];draw()}
function draw(){const forms={students:'<h2>Novo acolhimento</h2><form id="dataForm">'+field('Nome completo','name')+field('Data de entrada','date','date')+'<button>Cadastrar acolhido</button></form>',notes:'<h2>Registro individual</h2><form id="dataForm"><label>Acolhido</label><select id="stay" required>'+optionList()+'</select><label>Tipo</label><select id="category"><option value="rotina">Rotina</option><option value="ocorrencia">Ocorrência</option><option value="observacao">Observação</option></select><label>Relato</label><textarea id="description" required></textarea><p class="muted">É possível ditar pelo teclado do celular. O texto original será preservado.</p><button>Registrar</button></form>',trips:'<h2>Abrir viagem</h2><form id="dataForm">'+field('Motorista','driver')+'<label>Finalidade</label><select id="purpose"><option>Buscar doações</option><option>Culto</option><option>Consulta médica</option><option>Ressocialização</option><option>Compras</option><option>Outros</option></select>'+field('Destino','destination','text',false)+field('KM inicial','km','number')+field('Saída','departure','datetime-local')+'<button>Abrir viagem</button></form>'};el('formArea').innerHTML=forms[view];el('listArea').replaceChildren();if(!stays.length)el('listArea').textContent='Nenhum acolhido ativo cadastrado.';for(const s of stays){const item=document.createElement('div');item.className='item';const strong=document.createElement('strong');strong.textContent=s.crl_residents?.full_name||'Acolhido';const small=document.createElement('div');small.className='muted';small.textContent='Entrada: '+s.admission_date;item.append(strong,small);el('listArea').append(item)}el('dataForm').onsubmit=submit}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));draw()});
async function submit(e){e.preventDefault();if(!member||!user)return;const form=el('dataForm');const button=form.querySelector('button');button.disabled=true;status('Salvando...');try{let r;if(view==='students'){r=await db.rpc('crl_admit_resident',{p_institution:member.institution_id,p_name:el('name').value.trim(),p_date:el('date').value});}else if(view==='notes'){r=await db.from('crl_records').insert({institution_id:member.institution_id,stay_id:el('stay').value,category:el('category').value,original_text:el('description').value.trim(),author_id:user.id})}else{r=await db.from('crl_vehicle_trips').insert({institution_id:member.institution_id,driver_name:el('driver').value.trim(),purpose:el('purpose').value,destination:el('destination').value,km_initial:Number(el('km').value),departure_at:new Date(el('departure').value).toISOString(),created_by:user.id})}if(r.error)throw r.error;form.reset();status('Registro salvo com sucesso.');await refresh()}catch(error){status('Não foi possível salvar. Confira sua autorização ou os dados preenchidos.',true)}finally{button.disabled=false}}
init();